# Generated by Django 6.0.6 on 2026-06-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero_tekst',
            field=models.TextField(blank=True, null=True, verbose_name='Tekst hero'),
        ),
    ]
