# Generated by Django 6.0.6 on 2026-06-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_hero_tekst'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tytuł'),
        ),
    ]
