# Generated by Django 6.0.6 on 2026-06-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_images_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Baner'),
        ),
    ]
