# Generated by Django 6.0.5 on 2026-06-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Zdjęcie przed'),
        ),
        migrations.AddField(
            model_name='images',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Zdjęcie po'),
        ),
    ]
