# Generated by Django 6.0.5 on 2026-05-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa strony')),
                ('title', models.CharField(max_length=255, verbose_name='Meta title')),
                ('description', models.TextField(max_length=500, verbose_name='Meta description')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Meta keywords')),
                ('canonical_url', models.URLField(blank=True, null=True, verbose_name='Canonical URL')),
                ('robots', models.CharField(default='index, follow', max_length=100, verbose_name='Robots')),
                ('og_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open Graph title')),
                ('og_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Open Graph description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='meta/og/', verbose_name='Open Graph image')),
                ('og_url', models.URLField(blank=True, null=True, verbose_name='Open Graph URL')),
                ('og_type', models.CharField(default='website', max_length=50, verbose_name='Open Graph type')),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=50, verbose_name='Twitter card')),
                ('twitter_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter title')),
                ('twitter_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Twitter description')),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='meta/twitter/', verbose_name='Twitter image')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='meta/favicon/', verbose_name='Favicon')),
                ('theme_color', models.CharField(default='#000000', max_length=20, verbose_name='Theme color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'verbose_name': 'Meta strony',
                'verbose_name_plural': 'Meta stron',
            },
        ),
    ]
