# Generated by Django 6.0.5 on 2026-05-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='hero/', verbose_name='Image 1')),
                ('image3', models.ImageField(upload_to='hero/', verbose_name='Image 3')),
                ('image2', models.ImageField(upload_to='hero/', verbose_name='Image 2')),
                ('title1', models.CharField(max_length=255, verbose_name='Title 1')),
                ('title2', models.CharField(max_length=255, verbose_name='Title 2')),
            ],
            options={
                'verbose_name': 'Hero section',
                'verbose_name_plural': 'Hero sections',
            },
        ),
        migrations.RemoveField(
            model_name='sitemeta',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sitemeta',
            name='updated_at',
        ),
    ]
