# Generated by Django 6.0.5 on 2026-05-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_herosection_remove_sitemeta_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Image')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'O firmie',
                'verbose_name_plural': 'O firmie',
            },
        ),
        migrations.CreateModel(
            name='CtaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='cta/', verbose_name='Banner')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'CTA',
                'verbose_name_plural': 'CTA',
            },
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title 1'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title 2'),
        ),
    ]
