# Generated by Django 6.0.5 on 2026-05-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Certifikat',
                'verbose_name_plural': 'Certifikaty',
            },
        ),
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa firmy')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='adres')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='numer telefonu')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('maps', models.TextField(blank=True, null=True, verbose_name='Mapa')),
            ],
            options={
                'verbose_name': 'Company Data',
                'verbose_name_plural': 'Company Data',
            },
        ),
        migrations.CreateModel(
            name='Datenschutz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Datenschutz',
                'verbose_name_plural': 'Datenschutz',
            },
        ),
        migrations.CreateModel(
            name='Impressum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Impressum',
                'verbose_name_plural': 'Impressum',
            },
        ),
    ]
