# Generated by Django 6.0.5 on 2026-05-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='banner'),
        ),
    ]
