# Generated by Django 6.0.5 on 2026-06-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_companydata_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certifikat',
            options={'verbose_name': 'Certyfikat', 'verbose_name_plural': 'Certyfikaty'},
        ),
    ]
